[metadata]
name = longwave_terraform_git_hooks
version = 0.1.0
description = Git hooks riutilizzabili per progetti Terraform Longwave
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/llw-RnD/longwave-terraform-git-hooks
author = Longwave
author_email = innovation_r&d@longwave.it
license = MIT
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
packages = find:
install_requires =
    python-hcl2>=7.3.1
python_requires = >=3.10

[options.extras_require]
dev =
    pytest>=7.0.0
    pytest-cov>=4.0.0

[options.packages.find]
exclude =
    tests*

[options.entry_points]
console_scripts =
    check-terraform-naming = hooks.check_terraform_naming:main
    check-terraform-comments = hooks.check_terraform_comments:main
    check-terraform-locals-position = hooks.check_terraform_locals_position:main
